# Generated by Django 5.1.2 on 2024-10-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatOlahraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabang_olahraga', models.CharField(max_length=100)),
                ('alat_olahraga', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.CharField(max_length=20)),
                ('toko', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('gambar', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=500)),
                ('full_description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
    ]
