# Generated by Django 5.1 on 2024-10-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_moodentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='AlatOlahraga',
        ),
    ]
