# Generated by Django 5.1 on 2024-10-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_product_alatolahraga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alatolahraga',
            old_name='name',
            new_name='alat_olahraga',
        ),
        migrations.AddField(
            model_name='alatolahraga',
            name='cabang_olahraga',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
