# Generated by Django 5.1.4 on 2024-12-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alatolahraga_article_delete_moodentry'),
        ('main', '0003_rating_review'),
    ]

    operations = [
    ]
