# Generated by Django 5.1 on 2024-10-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_name_alatolahraga_alat_olahraga_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alatolahraga',
            old_name='description',
            new_name='deskripsi',
        ),
        migrations.RenameField(
            model_name='alatolahraga',
            old_name='image_url',
            new_name='gambar',
        ),
        migrations.RenameField(
            model_name='alatolahraga',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='alatolahraga',
            old_name='store',
            new_name='toko',
        ),
    ]
