# Generated by Django 5.1 on 2024-10-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_description_alatolahraga_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alatolahraga',
            name='harga',
            field=models.CharField(max_length=20),
        ),
    ]
